function [centroids, bboxes, time_elapsed] = detectObjects(detector_,...
    frame,...
    x,...
    y,...
    width,...
    height)

[centroids, bboxes, time_elapsed, image]=detect(detector_,...
    frame,...
    x,...
    y,...
    width,...
    height);
%imshow(image);
bboxes=[bboxes.x; bboxes.y; bboxes.width; bboxes.height;]';
centroids=[centroids.x; centroids.y;]';

end