function [centroids, bboxes, time_elapsed] = detectObjects(detector_,...
    frame,...
    x,...
    y,...
    width,...
    height,rois)

if isempty(rois)
[centroids, bboxes, time_elapsed]=detect(detector_,...
    frame,...
    x,...
    y,...
    width,...
    height);
else
[centroids, bboxes, time_elapsed]=detect_with_rois(detector_,...
    frame,...
    x,...
    y,...
    width,...
    height,...
    rois);
end
%imshow(image);
bboxes=[bboxes.x; bboxes.y; bboxes.width; bboxes.height;]';
centroids=[centroids.x; centroids.y;]';

end